// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeS4p0S-pKtbZyfG1ac2MtSTB0-0HN2hI',
    appId: '1:838607150724:web:54097be4d426cb43c72cd1',
    messagingSenderId: '838607150724',
    projectId: 'ggwallet-9add6',
    authDomain: 'ggwallet-9add6.firebaseapp.com',
    storageBucket: 'ggwallet-9add6.appspot.com',
    measurementId: 'G-MQZDBSTHWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjaFOzo9daGZrQgPRLYJbTjKK4DLoxzGE',
    appId: '1:838607150724:android:39863978ec5a49c3c72cd1',
    messagingSenderId: '838607150724',
    projectId: 'ggwallet-9add6',
    storageBucket: 'ggwallet-9add6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxrW7a-CGVOS8j76ycN3IkLmEbq7AnG_s',
    appId: '1:838607150724:ios:39c3ef66e86ed2dec72cd1',
    messagingSenderId: '838607150724',
    projectId: 'ggwallet-9add6',
    storageBucket: 'ggwallet-9add6.appspot.com',
    iosBundleId: 'com.example.ggWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxrW7a-CGVOS8j76ycN3IkLmEbq7AnG_s',
    appId: '1:838607150724:ios:02e4c870dda6cd86c72cd1',
    messagingSenderId: '838607150724',
    projectId: 'ggwallet-9add6',
    storageBucket: 'ggwallet-9add6.appspot.com',
    iosBundleId: 'com.example.ggWallet.RunnerTests',
  );
}
